spring.application.name=${SPRING_APPLICATION_NAME:parking-api-service}
server.port=${SERVER_PORT:8081}

parking.jwt.secret=${PARKING_JWT_SECRET:parking-development-secret-key-change-me-please-32bytes-minimum}

management.endpoints.web.exposure.include=health,info
management.endpoint.health.show-details=always
test=""