spring.application.name=parking-api-service
server.port=8081

parking.jwt.secret=parking-development-secret-key-change-me-please-32bytes-minimum

management.endpoints.web.exposure.include=health,info
management.endpoint.health.show-details=always